### ISSUE TITLE
MS Word compatible Error in LibreOffice

### ISSUE THREAD

**Issue by dti123** [Mendeley/openoffice-plugin#16]
Ubuntu 14.10 64-bit, LibreOffice 4.4.1.2, Python 2.7.8, Zip 3.0
Mendeley 1.13.6

Exporting MS Word compatible produces.
```
BASIC runtime error.
An exception occurred 
Type: com.sun.star.lang.IllegalArgumentException
Message: first parameter invalid.
```
Highlighting Line 138 of zoteroLib in LibreOffice BASIC

**Comment by elgitmariachi** [comment]
The same is happening to me.

**Comment by georgelappies** [comment]
Yeah, some happening to me as well

**Comment by ardiprakasa** [comment]
the same to me is happening

**Comment by rittman** [comment]
Me too I'm afraid. Almost identical versions of all software to that listed above.

**Comment by dmnfarrell** [comment]
Also occurs in Mendeley 1.14 with Libreoffice 4.4.2.2

**Comment by cpina** [comment]
I'll have a look soon and comment.

**Comment by cpina** [comment]
Hi - the ones that had the problem using LibreOffice 4.4: where did you install it from? PPA from Ubuntu or downloaded from libreoffice.org

Does it happen with a new document with a few citations or only if the document has a complex layout? (e.g. citations in tables, boxes, etc.).

I haven't been able to reproduce the problem yet.

**Comment by dmnfarrell** [comment]
I used the ubuntu ppa version and the document has about 50 citations but none in tables. There are images and tables in the document.

**Comment by rittman** [comment]
I also used the ppa-version of open-office. There were tables in the document. I wonder whether this may have something to do with tracking changes. Occasionally the plug-in has worked correctly when I've made some changes, accepted all changes and then updated the mendeley references and tried exporting to word, but this is inconsistent behaviour.

Regards,

Tim

On 25/06/15 18:35, Damien Farrell wrote:

I used the ubuntu ppa version and the document has about 50 citations but none in tables. There are images and tables in the document.

**Comment by cpina** [comment]
Hi - I had a look here. Using LibreOffice 4.4.3.2 (Build:2) from Ubuntu's PPA: I can reproduce the problem.
If I use LibreOffice 4.3.7.2 (Build:2) from libreoffice.org I can't reproduce the problem.
I'll investigate a bit more to know if it's a PPA issue (this happened in the past) or a LibreOffice.org version issue.

Meanwhile using 4.3.7.2 from libreoffice.org works correctly.

**Comment by cpina** [comment]
I've found the problem on LO: https://bugs.documentfoundation.org/show_bug.cgi?id=92420

I'll try to change Mendeley plugin code to avoid the problem (the code used to work but I'm unsure if it should ever have worked).

**Comment by cpina** [comment]
Hello again,

This should be working correctly using LibreOffice 4.4.4.3 (but not on 4.4.3.2).

Also, we've changed the code that didn't work correctly on LibreOffice 4.4.4.3 so when Mendeley Desktop 1.15-dev1 will be available it will work using LibreOffice 4.4.3.2 and 4.4.4.3.

If you wish to try the dev releases you can opt-in to the dev releases if you go to Mendeley Desktop -> Help -> Check for Updates -> Opt-in to experimental releases.

Any other problems let us know.

Regards,

**Comment by JLMcGuire** [comment]
Thank you!

**Comment by renatamuy** [comment]
Still happening in 2018 when editing the odt. So frustrating.

om.sun.star.lang.IllegalArgumentException
